### ISSUE TITLE
Do sweep of initial cooperator proportion

### ISSUE THREAD

**Issue by briandconnelly** [briandconnelly/nicheconstruct#80]
To address comments about evolution vs maintenance of cooperation, do a sweep of the initial cooperator proportion.

Initial results from short (100 cycle) simulations shows a lot of variation, but cooperators are increasing in frequency when rare. I'm sure the initial thinning is very important here.

![cooperator-change-100](https://cloud.githubusercontent.com/assets/658158/8965065/f9809442-35dd-11e5-820a-10e78330eec5.png)

- [x] Do simulations with 1%, 5%, and 10%.
    - Maybe others if the affect isn't linear.
- [x] Do simulations with 0%. Run these for longer and with more reps. Is it possible for cooperation to arise and spread?
- Combine data and create figure(s)
    - [x] Time series plot 
    - [x] Integral in each of the treatments? 
- Add relevant things to repository
    - [x] Configuration file(s)
    - [x] Data set
    - [x] Analysis scripts
    - [x] Figures

- [x] Increase number of replicates for p0 > 0 treatments.

**Comment by briandconnelly** [comment]
An update. Overall, the trend seems to show that cooperators increase in proportion.

![initialcoop_change-all](https://cloud.githubusercontent.com/assets/658158/9098166/f254af7e-3b7c-11e5-8f0f-f75615ce2b3e.png)

So far, no instances of cooperators arising de novo (from p0=0) and spreading, but if there are enough replicates, it may happen...

**Comment by briandconnelly** [comment]
One difficulty is that many populations with p0 < 0.5 start out with 0 cooperators. We may need to pay special consideration to these in the analysis.

**Comment by briandconnelly** [comment]
Would it be worth adding an option to the code to add a single (isolated) cooperator to an otherwise all-defector population at the beginning of the simulation? This would allow us to directly address the suggestion that we examine results when p0=1/800.

Or, is the fact that we have results for many simulations in which p0=0, so cooperators must arise *de novo*? More on those results later. Brief summary: Cooperators do not emerge and reach majority in any of the replicates that have been done so far. For this to happen, I think cooperators must arise VERY early on so that they have the ability to migrate to empty subpopulations.

**Comment by evokerr** [comment]
Dear Brian,

Have these been run with the standard number of subpopulations (or the
increased number)?  I wonder if this makes any difference...

Best,

Ben.

**Comment by briandconnelly** [comment]
Baseline, but I could get some runs going with the 10x smaller subpopulations setup done for the other paper.

**Comment by evokerr** [comment]
Might be worth checking out...

**Comment by briandconnelly** [comment]
Simulations submitted.

**Comment by evokerr** [comment]
That was quick!

**Comment by KatieDickinson** [comment]
If you have time (ha ha!) I like this idea "Would it be worth adding an option to the code to add a single (isolated) cooperator to an otherwise all-defector population at the beginning of the simulation?"

**Comment by briandconnelly** [comment]
Some nice results from simulations where the initial proportion of cooperators is 0 (and subpopulations are 10x smaller, while the population is ~10x larger):

![denovodrift-cooperators-time](https://cloud.githubusercontent.com/assets/658158/9571770/0b42b820-4f58-11e5-947b-77a9d80709ad.png)

Although these simulations were fairly short (each replicate takes about 43 hours to run), we do see cooperators emerging and increasing in abundance. This appears to happen more often here than without niche construction.

**Comment by briandconnelly** [comment]
This seems like this could be worth including in the Results section. We should discuss which parameters would be best:

- stay with the small populations?
- scale up to 3000 updates like the other simulations?

**Comment by KatieDickinson** [comment]
Scaling up to 3000 updates seems like it would be good idea but if each replicate takes about 43 hours to run, I'm not sure it is doable...
