### ISSUE TITLE
Making positive vs. negative niche construction more clear

### ISSUE THREAD

**Issue by sarahhammarlund** [briandconnelly/nicheconstruct#82]
Reviewer 1 said: "L262 The authors state that setting L=A changes the niche construction from positive to negative. I am afraid I completely missed the reasoning here and I think the paper would be improved if it were spelled out more clearly why this parameter setting induces positive niche construction (i.e. an increase in constructor fitness by their construction activity)."

I wonder if discussing positive and negative niche construction in the Methods section could help.  We could end the Niche Construction and Selective Feedbacks section with an explanation of how positive niche construction results from L = A and negative from L != A (like the one at L255).  And maybe we can also be more explicit that Box 1 explains this visually (it'd be interesting to know if more time with Box 1 would have helped reviewer 1).

**Comment by briandconnelly** [comment]
Handled. Description of the changes is in the response.
