### ISSUE TITLE
Past vs Present Tense in Results

### ISSUE THREAD

**Issue by briandconnelly** [briandconnelly/nicheconstruct#85]
Reviewer one said:

>L210 "performED" and I would argue results should be past tense throughout.

We can argue this was a stylistic choice, but our argument would be better if there is precedence. Look for articles in [Evolutionary Ecology](http://link.springer.com/journal/10682) that use present tense, particularly with models.

**Comment by sarahhammarlund** [comment]
I scanned through titles of Evol Ecol papers looking for modeling papers, and here's what I got from the past 2 years or so:

* http://link.springer.com/article/10.1007/s10682-014-9722-y/fulltext.html
Uses past tense to describe the model: "We used an agent based network model inspired by the work of..." but present tense in other places: "Each simulation run uses a standardised set of individuals in the first host generation." (A bit inconsistent actually but mostly past tense.)

* http://link.springer.com/article/10.1007/s10682-014-9728-5/fulltext.html
Present tense in Methods: "In this study, we define the midpoint of the phenotypic values..." but past tense in Results: "the magnitudes of plasticity in the predator population remained low to moderate..."

* http://link.springer.com/article/10.1007/s10682-014-9733-8/fulltext.html
Past tense in Methods: "We used a stochastic, spatially explicit framework..." and Results: "There was no evidence for phylogenetic signal..."

* http://link.springer.com/article/10.1007/s10682-012-9557-3/fulltext.html
Past tense throughout: "We modified the type of dependence..."

* http://link.springer.com/article/10.1007/s10682-014-9738-3/fulltext.html
Mostly past tense: "We simulated a 100-by-100 square grid with periodic boundary conditions..."

It seems like most people use past tense.  Some people use present tense to describe their model and then past tense to present results.  I wasn't able to find any papers that fully use present tense as we do, but I still like our stylistic choice... 

Maybe we could change just the first sentence of the results section ("we performed simulations...") but then keep the explanations in present tense ("cooperation increases subpopulation density...")?

**Comment by briandconnelly** [comment]
Thanks Sarah, these are helpful!

Sarah and Katie, what are your preferences for this? Stick with present tense, or switch to past? Past is probably more common, but present is a little bit more fun to read (and doesn't require a change).

**Comment by KatieDickinson** [comment]
I was going to say change to the past but, really I am fine with sticking with what we have (the present).

**Comment by briandconnelly** [comment]
Going to stick with present tense in the results, since a recent modeling paper in this journal used present. http://dx.doi.org/10.1007/s10682-015-9775-6
