### ISSUE TITLE
Simulations with Costs for Increased Population Size

### ISSUE THREAD

**Issue by briandconnelly** [briandconnelly/nicheconstruct#86]
Reviewer 1 commented:

>L172 / Eq 4 The costs and benefits of cooperation are always crucial in models like this, but while the costs are clear, the benefits are spread out using this equation. I feel like this should be clarified a little more - can the effects of this equation be reproduced in equation 2 such that both the costs and benefits of cooperation are explicitly expressed through effects on individual fitness?

A simple way to address this might be to use diminishing benefits, which can be done by raising the `p` parameter in the `S(p)` equation (Equation 4) to some power γ (a.k.a. gamma). Although it doesn't directly affect fitness, it does affect the c/b ratio.

![gamma-cost](https://cloud.githubusercontent.com/assets/658158/9014937/75d0182c-377a-11e5-9bdc-8e13146e2e6a.png)

In this plot, the green line shows `S(p)` as we have been using it in both papers. The red and ugly yellow-green lines show some diminishing returns. For a more complete picture, we could also do some runs with *accelerating* returns, which are the blue and purple lines.

- [x] Add gamma parameter to model (see 1b525077372151ed023f02e38d2338960fe6f571)
- [x] Add gamma to existing configuration files
- [x] Do simulations with diminishing returns. gamma={0.25, 0.5}
- [x] Do simulations with accelerating returns. gamma={1.5, 2.0}
- Combine data and create figure(s)
    - [x] Time series plot 
    - [x] Integral in each of the treatments? We haven't used the integral in this paper yet, so would require explanation
- [x] Add gamma to Table 1
- Add relevant things to repository
    - [x] Configuration file(s)
    - [x] Data set
    - [x] Analysis scripts
    - [x] Figures

**Comment by briandconnelly** [comment]
![returns_integral-all](https://cloud.githubusercontent.com/assets/658158/9176088/100c9ea4-3f3e-11e5-86c8-e98c20b2d12b.png)

**Comment by briandconnelly** [comment]
![cooperators-time-grouped-all](https://cloud.githubusercontent.com/assets/658158/9176097/263d55ce-3f3e-11e5-8896-ea8f315aaf30.png)

**Comment by briandconnelly** [comment]
Does anyone have any thoughts on what a good description of Gamma would be? I was thinking "Shape of Cooperative Benefit", but that might not be descriptive enough.

**Comment by KatieDickinson** [comment]
Ben just suggested "concavity of benefit function"  or "Shape perimeter of production function (or shape perimeter of the benefit function"
