### ISSUE TITLE
Our definition of cooperation

### ISSUE THREAD

**Issue by sarahhammarlund** [briandconnelly/nicheconstruct#87]
Reviewer 1: "L41 I think cooperation should be precisely defined here, with respect to the distinction between cooperation for mutual benefit (albeit with risk of defection), and altruism, whereby altruists always 'lose out' in the short term by their behaviour.  Which precisely do the authors think they are describing - it seems to me that it partly depends on the model parameters, but it is a bit difficult to tease out with the collective benefits conferred by Equation 4, but it seems more like altruism to me, and that's what the authors seem to suggest ('sacrificing their wellbeing to help others')?"

Could we take care of this by adding the sentence we used to have in the Hankshaw paper, which was:
"We define cooperation as costly behavior that improves the fitness of others (some authors use the term “altruism” for such behavior, e.g., West et al. 2007b)"?

Or I suppose another option is to just embrace the social semantics regime and use altruism, but that would involve lots and lots of changes.  Do we have more justification for using cooperation instead of altruism?

**Comment by briandconnelly** [comment]
Addressed in 3b33404a277572875d2c6a35a28dd60487ef0c82
