### ISSUE TITLE
Metapopulation and population

### ISSUE THREAD

**Issue by sarahhammarlund** [briandconnelly/nicheconstruct#88]
Reviewer 2: "Line 271 and others. At times the term 'population' used rather than subpopulation or metapopulation. This should be specified each time."

Hm, was it not clear that we're using population and subpopulation?  Should we just succumb to using metapopulation and subpopulation for clarity's sake?

**Comment by briandconnelly** [comment]
The conclusion that Ben and I came to is to triple check what we have for consistency, and put a note in the response about our choice. Meta population and subpopulation are an incorrect pair, so we shouldn't cave to that.

**Comment by sarahhammarlund** [comment]
Sounds good, agreed about meta/sub.
